services:
  - elasticsearch

language: java

jdk:
  - oraclejdk8

before_script:
  - sleep 10
  - curl ${ELASTIC_URL}

script:
  - ./gradlew check

after_success:
  - ./gradlew jacocoTestReport coveralls