services:
  - elasticsearch

env:
  - ELASTIC_URL="http://127.0.0.1:9200"

language: java

jdk:
  - oraclejdk8

before_script:
  - sleep 10

script:
  - ./gradlew check

after_success:
  - ./gradlew jacocoTestReport coveralls