/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ehongka' at '5/1/17 3:42 PM' with Gradle 2.13
 *
 * @author ehongka, @date 5/1/17 3:42 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
